export default [
  { id: '1', card: '5', color: 'blue' },
  { id: '2', card: '9', color: 'yellow' },
  { id: '3', card: 'draw4', color: 'special', special: true },
  { id: '4', card: 'draw2', color: 'green' },
  { id: '5', card: '4', color: 'blue' },
  { id: '6', card: '5', color: 'red' },
  { id: '7', card: 'change_color', color: 'special', special: true },
  { id: '8', card: '9', color: 'red' },
  { id: '9', card: '5', color: 'red' },
  { id: '10', card: '3', color: 'red' },
  { id: '11', card: '6', color: 'yellow' },
  { id: '12', card: '1', color: 'green' },
  { id: '13', card: 'jump', color: 'green' },
  { id: '14', card: 'jump', color: 'blue' },
  { id: '15', card: '3', color: 'blue' },
  { id: '16', card: 'invert', color: 'yellow' },
  { id: '17', card: '3', color: 'blue' },
  { id: '18', card: '3', color: 'blue' },
  { id: '19', card: '3', color: 'blue' },
  { id: '20', card: '3', color: 'blue' },
];
