name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '*.md'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  AWS_STAGE: api
  AWS_S3_BUCKET: univille-uno-www # Previously created bucket
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  deployApp:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Commit Checkout
        uses: actions/checkout@v2

      - name: install yarn
        run: npm i -g yarn

      - name: install app
        run: yarn --frozen-lockfile

      - name: build app
        run: yarn build

      - name: deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          SOURCE_DIR: './build'
